# Generated by Django 4.1.3 on 2023-01-24 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('Id_genome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('taille_sequence', models.CharField(blank=True, max_length=100, null=True)),
                ('sequence_genome', models.TextField(blank=True, null=True)),
                ('espece', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('mot_de_passe', models.CharField(max_length=30)),
                ('tel', models.IntegerField()),
                ('role', models.CharField(choices=[('annot', 'annotateur'), ('val', 'validateur'), ('user', 'utilisateur')], default='user', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gene_prot',
            fields=[
                ('nom_transcrit', models.TextField(max_length=100, primary_key=True, serialize=False)),
                ('nom_gene', models.CharField(max_length=100, null=True)),
                ('start_position', models.IntegerField()),
                ('end_position', models.IntegerField()),
                ('description', models.CharField(max_length=1000000, null=True)),
                ('sequence_nucleotidique', models.TextField(null=True)),
                ('sequence_peptidique', models.TextField(null=True)),
                ('Id_genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.genome')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estValide', models.BooleanField(default=False)),
                ('estAnnote', models.BooleanField(default=False)),
                ('commentaire', models.CharField(max_length=1000000, null=True)),
                ('Id_genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.genome')),
                ('emailAnnotateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emailAnnotateur', to='projet.utilisateur')),
                ('emailValidateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emailValidateur', to='projet.utilisateur')),
            ],
        ),
    ]
