# Generated by Django 4.1.3 on 2023-01-14 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('Id_genome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('contenu_genome', models.CharField(max_length=10000000)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('mot_de_passe', models.CharField(max_length=30)),
                ('tel', models.IntegerField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Validateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='proteine',
            fields=[
                ('nom_gene', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('start_position', models.IntegerField(max_length=30)),
                ('end_position', models.IntegerField(max_length=30)),
                ('sequence_peptidique', models.CharField(max_length=10000000)),
                ('Id_genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.genome')),
            ],
        ),
        migrations.AddField(
            model_name='genome',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.utilisateur'),
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('nom_gene', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('start_position', models.IntegerField(max_length=30)),
                ('end_position', models.IntegerField(max_length=30)),
                ('sequence_nucleotidique', models.CharField(max_length=10000000)),
                ('Id_genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.genome')),
            ],
        ),
        migrations.CreateModel(
            name='Chaine_prot',
            fields=[
                ('nom_gene', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000000)),
                ('Id_genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.genome')),
            ],
        ),
        migrations.CreateModel(
            name='Attribué',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_annot', models.CharField(max_length=100)),
                ('email_valid', models.CharField(max_length=100)),
                ('commentaire', models.CharField(max_length=1000000)),
                ('Id_genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.genome')),
            ],
        ),
        migrations.CreateModel(
            name='Annotaté',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espece', models.CharField(max_length=100)),
                ('Id_genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.genome')),
            ],
        ),
        migrations.CreateModel(
            name='Annotateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.utilisateur')),
            ],
        ),
    ]
