# Generated by Django 4.1.3 on 2023-01-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0002_delete_test_alter_gene_end_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='tel',
            field=models.IntegerField(),
        ),
    ]
