# Generated by Django 4.1.3 on 2023-01-14 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0003_alter_utilisateur_tel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotateur',
            old_name='email',
            new_name='emailAnnotateur',
        ),
        migrations.RenameField(
            model_name='validateur',
            old_name='email',
            new_name='emailValidateur',
        ),
    ]
