# Generated by Django 4.1.3 on 2023-01-14 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0004_rename_email_annotateur_emailannotateur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailAnnotateur', models.CharField(max_length=100, null=True)),
                ('emailValidateur', models.CharField(max_length=100, null=True)),
                ('estValide', models.BooleanField(default=False)),
                ('estAnnote', models.BooleanField(default=False)),
                ('commentaire', models.CharField(max_length=1000000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='gene_prot',
            fields=[
                ('nom_gene', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('start_position', models.IntegerField()),
                ('end_position', models.IntegerField()),
                ('description', models.CharField(max_length=1000000, null=True)),
                ('sequence_nucleotidique', models.TextField(null=True)),
                ('sequence_peptidique', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='annotaté',
            name='Id_genome',
        ),
        migrations.RemoveField(
            model_name='attribué',
            name='Id_genome',
        ),
        migrations.RemoveField(
            model_name='chaine_prot',
            name='Id_genome',
        ),
        migrations.RemoveField(
            model_name='gene',
            name='Id_genome',
        ),
        migrations.RemoveField(
            model_name='proteine',
            name='Id_genome',
        ),
        migrations.RemoveField(
            model_name='validateur',
            name='emailValidateur',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='contenu_genome',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='email',
        ),
        migrations.AddField(
            model_name='genome',
            name='sequence_genome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genome',
            name='taille_sequence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('annot', 'annotateur'), ('val', 'validateur'), ('user', 'utilisateur')], default='user', max_length=100),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Annotateur',
        ),
        migrations.DeleteModel(
            name='Annotaté',
        ),
        migrations.DeleteModel(
            name='Attribué',
        ),
        migrations.DeleteModel(
            name='Chaine_prot',
        ),
        migrations.DeleteModel(
            name='Gene',
        ),
        migrations.DeleteModel(
            name='proteine',
        ),
        migrations.DeleteModel(
            name='Validateur',
        ),
        migrations.AddField(
            model_name='gene_prot',
            name='Id_genome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.genome'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='Id_genome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.genome'),
        ),
    ]
